const DDB={hub:"https://hub.dronedb.app/r/islan-view-sas/sai",base:"https://hub.dronedb.app/orgs/islan-view-sas/ds/sai"};
const SAT={version:8,sources:{esri:{type:"raster",tiles:["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],tileSize:256,attribution:"© Esri"}},layers:[{id:"esri",type:"raster",source:"esri"}]};
const OSM={version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap contributors"}},layers:[{id:"osm",type:"raster",source:"osm"}]};
const center=[-81.7006,12.5847];let satellite=true,ddbNames=[];
const buildings={type:"FeatureCollection",features:[{type:"Feature",properties:{name:"Edificación demo"},geometry:{type:"Polygon",coordinates:[[[-81.705,12.5851],[-81.7045,12.5851],[-81.7045,12.5847],[-81.705,12.5847],[-81.705,12.5851]]]}}]};
const risk={type:"FeatureCollection",features:[{type:"Feature",properties:{name:"Zona demo"},geometry:{type:"Polygon",coordinates:[[[-81.709,12.589],[-81.702,12.590],[-81.699,12.586],[-81.705,12.583],[-81.709,12.589]]]}}]};
const projects={type:"FeatureCollection",features:[{type:"Feature",properties:{name:"Magic Garden",type:"Monitoreo RPAS"},geometry:{type:"Point",coordinates:[-81.721,12.564]}},{type:"Feature",properties:{name:"Lynval / Cove",type:"Fotogrametría"},geometry:{type:"Point",coordinates:[-81.724,12.536]}}]};
const map=new maplibregl.Map({container:"map",style:SAT,center,zoom:13.2,pitch:25,bearing:-8});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"bottom-left");map.addControl(new maplibregl.ScaleControl({unit:"metric"}),"bottom-left");
function core(){if(!map.getSource("b")){map.addSource("b",{type:"geojson",data:buildings});map.addLayer({id:"bf",type:"fill",source:"b",paint:{"fill-color":"#18a9c6","fill-opacity":.4}});map.addLayer({id:"bl",type:"line",source:"b",paint:{"line-color":"#baf3ff","line-width":1.5}})}if(!map.getSource("r")){map.addSource("r",{type:"geojson",data:risk});map.addLayer({id:"rf",type:"fill",source:"r",paint:{"fill-color":"#f0b44d","fill-opacity":.2}});map.addLayer({id:"rl",type:"line",source:"r",paint:{"line-color":"#ffd38a","line-width":2,"line-dasharray":[2,2]}})}if(!map.getSource("p")){map.addSource("p",{type:"geojson",data:projects});map.addLayer({id:"pc",type:"circle",source:"p",paint:{"circle-radius":7,"circle-color":"#a7d82e","circle-stroke-color":"#fff","circle-stroke-width":2}})}ddbNames.forEach(addDdbLayer)}
map.on("load",()=>{core();discoverDroneDB()});map.on("mousemove",e=>document.getElementById("coords").textContent=e.lngLat.lat.toFixed(5)+", "+e.lngLat.lng.toFixed(5));
function vis(ids,on){ids.forEach(id=>map.getLayer(id)&&map.setLayoutProperty(id,"visibility",on?"visible":"none"))}
document.querySelector("#toggle-buildings").onchange=e=>vis(["bf","bl"],e.target.checked);document.querySelector("#toggle-risk").onchange=e=>vis(["rf","rl"],e.target.checked);document.querySelector("#toggle-points").onchange=e=>vis(["pc"],e.target.checked);
document.querySelector("#btn-home").onclick=()=>map.flyTo({center,zoom:13.2,pitch:25,bearing:-8});document.querySelector("#btn-3d").onclick=()=>map.easeTo({pitch:60,bearing:20,duration:800});document.querySelector("#btn-clear").onclick=()=>{ddbNames.forEach(n=>vis(["ddb-"+safe(n)],false));document.querySelectorAll(".ddb-check").forEach(x=>x.checked=false)};
document.querySelector("#btn-style").onclick=()=>{satellite=!satellite;map.setStyle(satellite?SAT:OSM);map.once("style.load",core)};
const modal=document.querySelector("#ddb-modal");document.querySelector("#btn-ddb").onclick=()=>modal.classList.remove("hidden");document.querySelector("#btn-close").onclick=()=>modal.classList.add("hidden");modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};
function safe(s){return s.replace(/[^a-z0-9]/gi,"-").toLowerCase()}
function addDdbLayer(name){const id="ddb-"+safe(name);if(map.getSource(id))return;const u=DDB.base+"/wms?service=WMS&version=1.1.1&request=GetMap&layers="+encodeURIComponent(name)+"&styles=&bbox={bbox-epsg-3857}&width=256&height=256&srs=EPSG:3857&format=image/png&transparent=true";map.addSource(id,{type:"raster",tiles:[u],tileSize:256});map.addLayer({id,type:"raster",source:id,layout:{visibility:"none"},paint:{"raster-opacity":.92}})}
async function discoverDroneDB(){const box=document.querySelector("#ddb-layers"),dot=document.querySelector("#ddb-status");try{const r=await fetch(DDB.base+"/wms?service=WMS&request=GetCapabilities&version=1.3.0");if(!r.ok)throw Error(r.status);const xml=new DOMParser().parseFromString(await r.text(),"text/xml");const names=[...xml.querySelectorAll("Layer > Name")].map(n=>n.textContent.trim()).filter(Boolean);ddbNames=[...new Set(names)];if(!ddbNames.length)throw Error("Sin capas");box.innerHTML="";ddbNames.forEach(name=>{addDdbLayer(name);const row=document.createElement("label");row.className="layer-row";row.innerHTML='<input class="ddb-check" type="checkbox"><span>'+name+'</span>';row.querySelector("input").onchange=e=>vis(["ddb-"+safe(name)],e.target.checked);box.appendChild(row)});dot.className="dot ok"}catch(e){dot.className="dot fail";box.innerHTML='<div class="loading">No pude enumerar las capas por CORS o permisos. Puedes abrir el catálogo DroneDB aquí mismo; el visor queda preparado para WMS/WMTS.</div>'}}
map.on("click","pc",e=>{const p=e.features[0].properties;new maplibregl.Popup().setLngLat(e.lngLat).setHTML("<strong>"+p.name+"</strong><br><span>"+p.type+"</span>").addTo(map)});