(()=>{"use strict";
const q=new URLSearchParams(location.search),projectKey=q.get("project")||"sai-dronedb",path=q.get("path")||"",hash=q.get("hash")||"",rawType=Number(q.get("type")||0),$=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const TYPES={DIRECTORY:1,GENERIC:2,GEOIMAGE:3,GEORASTER:4,POINTCLOUD:5,IMAGE:6,DRONEDB:7,MARKDOWN:8,VIDEO:9,GEOVIDEO:10,MODEL:11,PANORAMA:12,GEOPANORAMA:13,VECTOR:14,GAUSSIAN_SPLAT:15,TILES3D:16},NAMES={2:"Archivo",3:"Fotografía georreferenciada",4:"GeoTIFF / GeoRaster",5:"Nube de puntos",6:"Fotografía",8:"Documento",9:"Video",10:"Video georreferenciado",11:"Modelo 3D",12:"Panorama",13:"Panorama georreferenciado",14:"Vector GIS",15:"Gaussian Splat",16:"3D Tiles"};
let project=null,base="",entry={path,hash,type:rawType},siblings=[],map=null,drawMode=null,coords=[],drawSourceReady=false;
function ext(p){return(String(p||"").split(".").pop()||"").toLowerCase()}
function inferType(e){if(e.type)return e.type;const x=ext(e.path);if(["tif","tiff"].includes(x))return TYPES.GEORASTER;if(["las","laz","copc"].includes(x))return TYPES.POINTCLOUD;if(["obj","glb","gltf","fbx","ply"].includes(x))return TYPES.MODEL;if(["geojson","json","kml","kmz","gpkg","shp"].includes(x))return TYPES.VECTOR;if(["jpg","jpeg","png","webp"].includes(x))return TYPES.IMAGE;if(["mp4","mov","webm"].includes(x))return TYPES.VIDEO;return TYPES.GENERIC}
function icon(e){const t=inferType(e);return t===4?"▧":t===5?"◌":[11,15,16].includes(t)?"◇":t===14?"⌑":[3,6,12,13].includes(t)?"◉":[9,10].includes(t)?"▶":"▤"}
function name(e){return e.name||String(e.path||"").split("/").pop()||"Producto"}
function parentPath(p){const a=String(p||"").split("/");a.pop();return a.join("/")}
function inlineUrl(p){return base+"/download/"+String(p||"").split("/").map(encodeURIComponent).join("/")+"?inline=1"}
function thumbUrl(p){return base+"/thumb?path="+encodeURIComponent(p)+"&size=640"}
function productUrl(e){return"./product-viewer.html?project="+encodeURIComponent(projectKey)+"&path="+encodeURIComponent(e.path||"")+"&hash="+encodeURIComponent(e.hash||"")+"&type="+encodeURIComponent(inferType(e))}
function status(t){$("#pv-status").textContent=t}
function fail(e){console.error(e);$("#pv-loading").classList.add("hidden");$("#pv-error").textContent=e.message||String(e);$("#pv-error").classList.remove("hidden");status("Error al abrir producto")}
async function list(p=""){const f=new FormData();if(p)f.append("path",p);const r=await fetch(base+"/list",{method:"POST",body:f,credentials:"omit"});if(!r.ok)throw Error("DroneDB respondió "+r.status);return r.json()}
async function getJSON(p){const r=await fetch(base+p,{credentials:"omit"});if(!r.ok)throw Error("DroneDB respondió "+r.status);return r.json()}
async function loadProject(){const r=await fetch("./projects.json",{cache:"no-cache"}),j=await r.json();project=(j.projects||[]).find(x=>x.id===projectKey);if(!project?.dronedb)throw Error("Proyecto DroneDB no disponible");const d=project.dronedb;base=String(d.registry||"https://hub.dronedb.app").replace(/\/$/,"")+"/orgs/"+encodeURIComponent(d.org)+"/ds/"+encodeURIComponent(d.dataset);const back="./dataset-explorer.html?project="+encodeURIComponent(projectKey);$("#pv-back").href=back;$("#pv-close").href=back;$("#pv-breadcrumb").textContent=(d.dataset||projectKey).toUpperCase()+" / PRODUCTO"}
async function resolveEntry(){const rows=await list(parentPath(path));siblings=(rows||[]).filter(e=>e.type!==TYPES.DIRECTORY&&e.type!==TYPES.DRONEDB);const exact=siblings.find(e=>e.path===path);if(exact)entry={...exact};else entry={path,hash,type:rawType};entry.type=inferType(entry);entry.hash=entry.hash||hash;renderFiles();renderHeader()}
function renderFiles(){const term=$("#pv-search").value.trim().toLowerCase(),rows=siblings.filter(e=>!term||name(e).toLowerCase().includes(term));$("#pv-file-list").innerHTML=rows.map(e=>'<div class="pv-file '+(e.path===entry.path?"active":"")+'" data-path="'+esc(e.path)+'"><i>'+icon(e)+'</i><span><strong>'+esc(name(e))+'</strong><small>'+esc(NAMES[inferType(e)]||ext(e.path)||"producto")+'</small></span></div>').join("")||'<div class="pv-loading-row">No hay otros productos en esta carpeta.</div>';$("#pv-file-list").querySelectorAll("[data-path]").forEach(x=>x.onclick=()=>{const e=siblings.find(y=>y.path===x.dataset.path);if(e)location.href=productUrl(e)})}
function renderHeader(){document.title="Island View · "+name(entry);$("#pv-name").textContent=name(entry);$("#pv-kind").textContent=(NAMES[entry.type]||"Producto")+" · "+(ext(entry.path).toUpperCase()||"DroneDB");const dl=inlineUrl(entry.path);$("#pv-download").href=dl;$("#pv-download").download="";$("#pv-open-source").href=dl;$("#pv-preview").innerHTML=[3,4,6,12,13].includes(entry.type)?'<img src="'+esc(thumbUrl(entry.path))+'" alt="">':'<div style="font-size:48px;color:#6d8791">'+icon(entry)+'</div>';const rows=[["Nombre",name(entry)],["Tipo",NAMES[entry.type]||entry.type],["Formato",ext(entry.path).toUpperCase()||"—"],["Ruta",entry.path],["Hash",entry.hash||"—"],["Motor",engineName(entry)]];$("#pv-props").innerHTML=rows.map(([a,b])=>'<div class="pv-prop"><span>'+esc(a)+'</span><b>'+esc(b)+'</b></div>').join("")}
function engineName(e){if(e.type===5)return"Potree · COPC";if([11,16].includes(e.type))return"Giro3D / 3D Tiles";if([3,4,14].includes(e.type))return"MapLibre GIS";if([6,12,13].includes(e.type))return"Image Viewer";if([9,10].includes(e.type))return"Video Viewer";return"DroneDB file preview"}
function showEngine(id){["#pv-map","#pv-frame","#pv-media"].forEach(s=>$(s).classList.add("hidden"));$(id).classList.remove("hidden");$("#pv-loading").classList.add("hidden")}
function productId(e){return"ddb-"+String(e.hash||e.path).replace(/[^a-zA-Z0-9_-]/g,"").slice(0,80)}
function openFrame(url,label){$("#pv-frame").src=url;$("#pv-engine-label").textContent=label;$("#pv-frame").onload=()=>{showEngine("#pv-frame");status(label+" listo")}}
function initMap(){if(map)return;map=new maplibregl.Map({container:"pv-map",style:{version:8,sources:{sat:{type:"raster",tiles:["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],tileSize:256,attribution:"Esri World Imagery"}},layers:[{id:"sat",type:"raster",source:"sat"}]},center:project?.coordinates||[-81.7006,12.5847],zoom:13,maxZoom:22});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"bottom-right");map.addControl(new maplibregl.ScaleControl({unit:"metric"}),"bottom-left");map.on("mousemove",e=>$("#pv-coords").textContent=e.lngLat.lat.toFixed(6)+", "+e.lngLat.lng.toFixed(6));map.on("load",()=>{ensureDraw();loadMapProduct().catch(fail)});map.on("click",handleMapClick);map.on("dblclick",e=>{if(["distance","area","stats"].includes(drawMode)){e.preventDefault();finishDraw()}});$("#pv-map-tools").classList.remove("hidden");$("#pv-engine-label").textContent="GIS"}
function ensureDraw(){if(drawSourceReady)return;map.addSource("pv-draw",{type:"geojson",data:{type:"FeatureCollection",features:[]}});map.addLayer({id:"pv-draw-fill",type:"fill",source:"pv-draw",filter:["==",["geometry-type"],"Polygon"],paint:{"fill-color":"#19b7d1","fill-opacity":.2}});map.addLayer({id:"pv-draw-line",type:"line",source:"pv-draw",paint:{"line-color":"#8debf3","line-width":3}});map.addLayer({id:"pv-draw-points",type:"circle",source:"pv-draw",filter:["==",["geometry-type"],"Point"],paint:{"circle-radius":5,"circle-color":"#a8d64b","circle-stroke-color":"#fff","circle-stroke-width":2}});drawSourceReady=true}
function drawFC(){const fs=coords.map(c=>turf.point(c));if(coords.length>1)fs.push(turf.lineString(coords));if(["area","stats"].includes(drawMode)&&coords.length>2)fs.push(turf.polygon([[...coords,coords[0]]]));map.getSource("pv-draw").setData({type:"FeatureCollection",features:fs})}
async function handleMapClick(e){if(!drawMode)return;if(drawMode==="inspect"){if(entry.type===4)try{const v=await getJSON("/raster-point-value?path="+encodeURIComponent(entry.path)+"&x="+e.lngLat.lng+"&y="+e.lngLat.lat);measure("Valor raster",JSON.stringify(v));}catch(err){measure("Coordenada",e.lngLat.lng.toFixed(7)+", "+e.lngLat.lat.toFixed(7))}else measure("Coordenada",e.lngLat.lng.toFixed(7)+", "+e.lngLat.lat.toFixed(7));return}coords.push([e.lngLat.lng,e.lngLat.lat]);drawFC()}
function measure(title,value){$("#pv-measure").innerHTML="<strong>"+esc(title)+"</strong><div>"+esc(value)+"</div>";$("#pv-measure").classList.remove("hidden")}
async function finishDraw(){if(drawMode==="distance"&&coords.length>1){const l=turf.length(turf.lineString(coords),{units:"kilometers"});measure("Distancia",l<1?(l*1000).toFixed(2)+" m":l.toFixed(3)+" km")}if(drawMode==="area"&&coords.length>2){const a=turf.area(turf.polygon([[...coords,coords[0]]]));measure("Área",a>=10000?(a/10000).toFixed(4)+" ha":a.toFixed(2)+" m²")}if(drawMode==="stats"&&coords.length>1&&entry.type===4){const bb=turf.bbox(turf.lineString(coords));try{const st=await getJSON("/raster-area-stats?path="+encodeURIComponent(entry.path)+"&x0="+bb[0]+"&y0="+bb[1]+"&x1="+bb[2]+"&y1="+bb[3]);measure("Estadísticas","Min "+st.min+" · Max "+st.max+" · Media "+st.mean+" · Mediana "+st.median)}catch(e){measure("Estadísticas",e.message)}}drawMode=null;document.querySelectorAll("[data-tool]").forEach(b=>b.classList.remove("active"))}
async function loadMapProduct(){if(entry.type===4){map.addSource("product",{type:"raster",tiles:[base+"/tiles/{z}/{x}/{y}.png?path="+encodeURIComponent(entry.path)],tileSize:256});map.addLayer({id:"product",type:"raster",source:"product",paint:{"raster-opacity":.98}});const g=entry.polygon_geom;if(g)try{const bb=turf.bbox({type:"Feature",geometry:g,properties:{}});map.fitBounds([[bb[0],bb[1]],[bb[2],bb[3]]],{padding:55,maxZoom:20})}catch{}status("GeoRaster sobre imagen satelital")}else if(entry.type===14&&entry.hash){const meta=await getJSON("/mvt/"+encodeURIComponent(entry.hash)+"/metadata.json"),layers=meta.vector_layers||[];map.addSource("product",{type:"vector",tiles:[base+"/mvt/"+encodeURIComponent(entry.hash)+"/{z}/{x}/{y}.pbf"],maxzoom:meta.maxzoom||18});for(const [i,l] of layers.entries()){const sl=l.id;map.addLayer({id:"vf"+i,type:"fill",source:"product","source-layer":sl,filter:["==",["geometry-type"],"Polygon"],paint:{"fill-color":"#19b7d1","fill-opacity":.22,"fill-outline-color":"#b5f3f8"}});map.addLayer({id:"vl"+i,type:"line",source:"product","source-layer":sl,filter:["==",["geometry-type"],"LineString"],paint:{"line-color":"#7de3ec","line-width":2.5}});map.addLayer({id:"vp"+i,type:"circle",source:"product","source-layer":sl,filter:["==",["geometry-type"],"Point"],paint:{"circle-radius":5,"circle-color":"#a8d64b","circle-stroke-color":"#fff","circle-stroke-width":1.5}})}for(let i=0;i<layers.length;i++)for(const id of["vf"+i,"vl"+i,"vp"+i])map.on("click",id,e=>{const p=e.features?.[0]?.properties||{},rows=Object.entries(p).slice(0,14).map(([k,v])=>"<tr><th style=\"text-align:left;padding-right:8px\">"+esc(k)+"</th><td>"+esc(v)+"</td></tr>").join("");new maplibregl.Popup({maxWidth:"360px"}).setLngLat(e.lngLat).setHTML("<strong>"+esc(name(entry))+"</strong><table style=\"font-size:10px;margin-top:6px\">"+rows+"</table>").addTo(map)});if(meta.bounds?.length===4)map.fitBounds([[meta.bounds[0],meta.bounds[1]],[meta.bounds[2],meta.bounds[3]]],{padding:50,maxZoom:18});status("Vector MVT sobre imagen satelital")}else if(entry.type===3){const g=entry.point_geom;if(g?.coordinates){new maplibregl.Marker().setLngLat(g.coordinates.slice(0,2)).setPopup(new maplibregl.Popup().setHTML('<img src="'+esc(thumbUrl(entry.path))+'" style="width:220px;max-width:100%">')).addTo(map);map.flyTo({center:g.coordinates.slice(0,2),zoom:19})}status("Fotografía georreferenciada")}showEngine("#pv-map")}
function openMedia(){const u=inlineUrl(entry.path),x=ext(entry.path),box=$("#pv-media");if([6,12,13].includes(entry.type)||["jpg","jpeg","png","webp","gif"].includes(x))box.innerHTML='<img src="'+esc(u)+'" alt="">';else if([9,10].includes(entry.type)||["mp4","mov","webm"].includes(x))box.innerHTML='<video src="'+esc(u)+'" controls playsinline></video>';else if(x==="pdf")box.innerHTML='<iframe src="'+esc(u)+'"></iframe>';else box.innerHTML='<div style="color:#b8c9ce;text-align:center"><div style="font-size:58px">'+icon(entry)+'</div><h3>'+esc(name(entry))+'</h3><p>Este archivo puede descargarse o abrirse desde sus propiedades.</p><a href="'+esc(u)+'" style="color:#72dce7">Abrir archivo original</a></div>';$("#pv-engine-label").textContent="MEDIA";showEngine("#pv-media");status("Producto abierto")}
function openProduct(){if([3,4,14].includes(entry.type)){initMap();return}if(entry.type===5){openFrame("./pointcloud-viewer.html?embedded=1&project="+encodeURIComponent(projectKey)+"&path="+encodeURIComponent(entry.path)+"&hash="+encodeURIComponent(entry.hash||""),"POTREE");return}if([11,16].includes(entry.type)){openFrame("./unified-viewer.html?embedded=1&mode=product&project="+encodeURIComponent(projectKey)+"&path="+encodeURIComponent(entry.path)+"&product="+encodeURIComponent(productId(entry)),"3D");return}openMedia()}
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{const t=b.dataset.tool;if(t==="clear"){coords=[];drawMode=null;if(drawSourceReady)map.getSource("pv-draw").setData({type:"FeatureCollection",features:[]});$("#pv-measure").classList.add("hidden");document.querySelectorAll("[data-tool]").forEach(x=>x.classList.remove("active"));return}drawMode=t;coords=[];document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b));status(t==="inspect"?"Toca el producto para consultar":"Toca para añadir vértices · doble clic/toque para finalizar")});
$("#pv-search").oninput=renderFiles;$("#pv-info-btn").onclick=()=>$("#pv-info").classList.toggle("hidden");$("#pv-info-close").onclick=()=>$("#pv-info").classList.add("hidden");$("#pv-full").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();$("#pv-files-toggle").onclick=()=>document.querySelector(".pv-shell").classList.toggle("files-collapsed");
(async()=>{try{await loadProject();await resolveEntry();openProduct()}catch(e){fail(e)}})();
})();